spring:
  application:
    name: coffeemachineconfigsrv
  datasource:
    url: jdbc:mysql://localhost:3306/coffeesmachinecloud?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}e9f8f0916e4542d58662c9811629961f75397711159b0e02655cd30623734371c6bc7a9acf9844635235f4b9e6bb34c6"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
